# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/pynq/pynq.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq || ORIG_REF_NAME==pynq} -quiet] -quiet

# IP: bd/pynq/ip/pynq_ntt_dma_translator_0_0/pynq_ntt_dma_translator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_ntt_dma_translator_0_0 || ORIG_REF_NAME==pynq_ntt_dma_translator_0_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_mlkem_mmio_0_0/pynq_mlkem_mmio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_mlkem_mmio_0_0 || ORIG_REF_NAME==pynq_mlkem_mmio_0_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_ntt_ctrl_parser_0_0/pynq_ntt_ctrl_parser_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_ntt_ctrl_parser_0_0 || ORIG_REF_NAME==pynq_ntt_ctrl_parser_0_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_ntt_top_0_0/pynq_ntt_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_ntt_top_0_0 || ORIG_REF_NAME==pynq_ntt_top_0_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_processing_system7_0_0/pynq_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_processing_system7_0_0 || ORIG_REF_NAME==pynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_axi_dma_0_0/pynq_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_axi_dma_0_0 || ORIG_REF_NAME==pynq_axi_dma_0_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_xbar_0/pynq_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_xbar_0 || ORIG_REF_NAME==pynq_xbar_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_ps7_0_axi_periph_1/pynq_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_ps7_0_axi_periph_1 || ORIG_REF_NAME==pynq_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/pynq/ip/pynq_rst_ps7_0_100M_1/pynq_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_rst_ps7_0_100M_1 || ORIG_REF_NAME==pynq_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/pynq/ip/pynq_xbar_1/pynq_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_xbar_1 || ORIG_REF_NAME==pynq_xbar_1} -quiet] -quiet

# IP: bd/pynq/ip/pynq_axi_mem_intercon_0/pynq_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_axi_mem_intercon_0 || ORIG_REF_NAME==pynq_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_system_ila_0_1/pynq_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_system_ila_0_1 || ORIG_REF_NAME==pynq_system_ila_0_1} -quiet] -quiet

# Block Designs: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_system_ila_0_1/bd_0/bd_a20f.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a20f || ORIG_REF_NAME==bd_a20f} -quiet] -quiet

# IP: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_system_ila_0_1/bd_0/ip/ip_0/bd_a20f_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a20f_ila_lib_0 || ORIG_REF_NAME==bd_a20f_ila_lib_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_util_vector_logic_0_0/pynq_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_util_vector_logic_0_0 || ORIG_REF_NAME==pynq_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_auto_pc_0/pynq_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_auto_pc_0 || ORIG_REF_NAME==pynq_auto_pc_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_auto_us_0/pynq_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_auto_us_0 || ORIG_REF_NAME==pynq_auto_us_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_auto_us_1/pynq_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_auto_us_1 || ORIG_REF_NAME==pynq_auto_us_1} -quiet] -quiet

# IP: bd/pynq/ip/pynq_auto_pc_1/pynq_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pynq_auto_pc_1 || ORIG_REF_NAME==pynq_auto_pc_1} -quiet] -quiet

# XDC: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_processing_system7_0_0/pynq_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynq_processing_system7_0_0 || ORIG_REF_NAME==pynq_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_axi_dma_0_0/pynq_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynq_axi_dma_0_0 || ORIG_REF_NAME==pynq_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_axi_dma_0_0/pynq_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynq_axi_dma_0_0 || ORIG_REF_NAME==pynq_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_rst_ps7_0_100M_1/pynq_rst_ps7_0_100M_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynq_rst_ps7_0_100M_1 || ORIG_REF_NAME==pynq_rst_ps7_0_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_rst_ps7_0_100M_1/pynq_rst_ps7_0_100M_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynq_rst_ps7_0_100M_1 || ORIG_REF_NAME==pynq_rst_ps7_0_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a20f_ila_lib_0 || ORIG_REF_NAME==bd_a20f_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a20f_ila_lib_0 || ORIG_REF_NAME==bd_a20f_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_system_ila_0_1/bd_0/ip/ip_0/bd_a20f_ila_lib_0_ooc.xdc

# XDC: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_system_ila_0_1/bd_0/bd_a20f_ooc.xdc

# XDC: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_auto_pc_0/pynq_auto_pc_0_ooc.xdc

# XDC: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_auto_us_0/pynq_auto_us_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynq_auto_us_0 || ORIG_REF_NAME==pynq_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_auto_us_0/pynq_auto_us_0_ooc.xdc

# XDC: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_auto_us_1/pynq_auto_us_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynq_auto_us_1 || ORIG_REF_NAME==pynq_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_auto_us_1/pynq_auto_us_1_ooc.xdc

# XDC: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/ip/pynq_auto_pc_1/pynq_auto_pc_1_ooc.xdc

# XDC: d:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.gen/sources_1/bd/pynq/pynq_ooc.xdc
