webtalk_init -webtalk_dir D:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.sim/sim_1/behav/xsim/xsim.dir/tb_ntt_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr 29 04:02:07 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6c39852b-1b9c-4d21-8c38-e5347407dc8e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "93b8201845e246e69e456dd114786c61" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-12450H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "107955 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.25_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9412_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3341377800 -regid "" -xml D:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.sim/sim_1/behav/xsim/xsim.dir/tb_ntt_top_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.sim/sim_1/behav/xsim/xsim.dir/tb_ntt_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/download/downloads/embedded_sys_project/vivado/ntt_verilog_codes/NTT/NTT.sim/sim_1/behav/xsim/xsim.dir/tb_ntt_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
